# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: viduzx
      POSTGRES_DB: mydb
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
